# Generated by Django 2.2.4 on 2019-08-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksdemo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
